- locale: it
- display: short

- dictionary:
    test_ciao-it: "ciao"
    test_ciao-en-long: "ciaone"

- include-dictionary:
    file: util/dictionary.yml

- include-header:
    file: util/header.yml

- include-section-education:
    file: sections/education.yml
    display:
      bachelor: long
    order:
      _: 2
      high-school: 1

- include-section-award:
    file: sections/award.yml
