- locale: en
- display: long

- include-dictionary:
    file: util/dictionary.yml

- include-header:
    file: util/header.yml

- header:
    summary:
      title-en: Summary
      title-it: Riassunto
      summary: I like writing books about robots.

- include-section-education:
    file: sections/education.yml
    display:
      bachelor: long
    order:
      _: 2
      high-school: 1
    visibility:
      this-is-invisible: false

- include-section-award:
    file: sections/award.yml
